name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npx tsc -noEmit -skipLibCheck

      - name: ESLint check
        run: npx eslint . --ext .ts,.js --max-warnings 0
        continue-on-error: true

      - name: Check for TypeScript compilation errors
        run: |
          echo "Running TypeScript compilation check..."
          if ! npx tsc -noEmit -skipLibCheck; then
            echo "❌ TypeScript compilation failed"
            exit 1
          else
            echo "✅ TypeScript compilation successful"
          fi

  build-test:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Verify build artifacts
        run: |
          echo "Checking build output..."
          if [ ! -d "build" ]; then
            echo "❌ Build directory not found"
            exit 1
          fi

          if [ ! -f "build/main.js" ]; then
            echo "❌ main.js not found in build output"
            exit 1
          fi

          if [ ! -f "build/manifest.json" ]; then
            echo "❌ manifest.json not found in build output"
            exit 1
          fi

          if [ ! -f "build/styles.css" ]; then
            echo "❌ styles.css not found in build output"
            exit 1
          fi

          echo "✅ All required build artifacts present"
          echo "Build directory contents:"
          ls -la build/

          # Check if main.js is not empty
          if [ ! -s "build/main.js" ]; then
            echo "❌ main.js is empty"
            exit 1
          fi

          echo "✅ Build verification complete"

      - name: Test plugin loading
        run: |
          echo "Checking if main.js is valid JavaScript..."
          node -c build/main.js && echo "✅ main.js syntax is valid" || (echo "❌ main.js has syntax errors" && exit 1)

      - name: Validate manifest.json
        run: |
          echo "Validating manifest.json..."
          node -e "
            const fs = require('fs');
            const manifest = JSON.parse(fs.readFileSync('build/manifest.json', 'utf8'));

            const required = ['id', 'name', 'version', 'minAppVersion', 'description', 'author'];
            const missing = required.filter(field => !manifest[field]);

            if (missing.length > 0) {
              console.log('❌ Missing required fields in manifest.json:', missing.join(', '));
              process.exit(1);
            }

            console.log('✅ manifest.json is valid');
            console.log('Plugin info:', {
              id: manifest.id,
              name: manifest.name,
              version: manifest.version,
              author: manifest.author
            });
          "
